baseURL = "https://example.org"
title = 'Babalar Press'

disableKinds = ["page", "section", "taxonomy", "term"]

[module]
  [module.hugoVersion]
    extended = true
    min      = "0.112.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"

defaultContentLanguage = 'kz'
defaultContentLanguageInSubdir = true

[languages]

  [languages.kz]
    contentDir = 'content/kazakh'
    languageCode = 'kz'
    languageName = 'KZ'
    weight = 10

    [[languages.kz.menu.main]]
      name = 'Басты бет'
      url = '/'

    [[languages.kz.menu.main]]
      name = 'Біз жайлы'
      url = '/about'

    [[languages.kz.menu.main]]
      name = 'Бізбен хабарлас'
      url = '/contact'

  [languages.en]
    contentDir = 'content/english'
    languageCode = 'en'
    languageName = 'EN'
    weight = 20

    [[languages.en.menu.main]]
      name = 'Home'
      url = '/'

    [[languages.en.menu.main]]
      name = 'About'
      url = '/about'

    [[languages.en.menu.main]]
      name = 'Contact'
      url = '/contact'

  [languages.ru]  
    contentDir = 'content/russian'
    languageCode = 'RU'
    languageName = 'Russian'
    weight = 30

    [[languages.ru.menu.main]]
      name = 'Главная'
      url = '/'

    [[languages.ru.menu.main]]
      name = 'О нас'
      url = '/about'

    [[languages.ru.menu.main]]
      name = 'Связаться с нами'
      url = '/contact'

