baseURL = "https://babalar-press.github.io/bp"
canonifyurls = true
relativeURLs = "True"
title = 'Babalar Press'


[module]
  [module.hugoVersion]
    extended = true
    min      = "0.112.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"



defaultContentLanguage = 'kk-KZ'
defaultContentLanguageInSubdir = false

[languages]

  [languages.kz]
    contentDir = 'content/kz'
    disabled = false
    languageCode = 'kk-KZ'
    languageName = 'kz'
    weight = 1

  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageName = 'en'
    weight = 2

  [languages.ru]  
    contentDir = 'content/ru'
    disabled = false
    languageCode = 'ru-RU'
    languageName = 'ru'
    weight = 3


    [[menu.main]]
      identifier = 'home'
      url = '/'
      weight = 10

    [[menu.main]]
      identifier = 'about'
      url = '/about'
      weight = 20

    [[menu.main]]
      identifier = 'contact'
      url = '/contact'
      weight = 40

     [[menu.main]]
      identifier = 'publications'
      url = '/publications'
      weight = 30


    [[menu.main]]
      identifier = 'home'
      url = '/'
      weight = 10

    [[menu.main]]
      identifier = 'about'
      url = '/about'
      weight = 20

    [[menu.main]]
      identifier = 'contact'
      url = '/contact'
      weight = 40

     [[menu.main]]
      identifier = 'publications'
      url = '/publications'
      weight = 30

    [[menu.main]]
      identifier = 'home'
      url = '/'
      weight = 10   

    [[menu.main]]
      identifier = 'about'
      url = '/about'
      weight = 20

    [[menu.main]]
      identifier = 'contact'
      url = '/contact'
      weight = 40

    [[menu.main]]
      identifier = 'publications'
      url = '/publications'
      weight = 30

