baseURL = "https://example.org"
title = 'Babalar Press'

disableKinds = ["page", "section", "taxonomy", "term"]

[module]
  [module.hugoVersion]
    extended = true
    min      = "0.112.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"

defaultContentLanguage = 'kz'
defaultContentLanguageInSubdir = true

[languages]

  [languages.kz]
    contentDir = 'content/kazakh'
    languageCode = 'kz'
    languageName = 'KZ'
    weight = 10

  [languages.en]
    contentDir = 'content/english'
    languageCode = 'en'
    languageName = 'EN'
    weight = 20

  [languages.ru]  
    contentDir = 'content/russian'
    languageCode = 'ru'
    languageName = 'Russian'
    weight = 30


    [[menu.main]]
      identifier = 'home'
      url = '/'
      weight = '2'

    [[menu.main]]
      identifier = 'about'
      url = '/about'
      weight = '7'

    [[menu.main]]
      identifier = 'contact'
      url = '/contact'
      weight = 9


    [[menu.main]]
      identifier = 'home'
      url = '/en/'
      weight = 11

    [[menu.main]]
      identifier = 'about'
      url = 'en/about/'
      weight = 13

    [[menu.main]]
      identifier = 'contact'
      url = 'en/contact/'
      weight = 15

    [[menu.main]]
      identifier = 'home'
      url = '/ru'
      weight = 17

    [[menu.main]]
      identifier = 'about'
      url = 'ru/about/'
      weight = 19

    [[menu.main]]
      identifier = 'contact'
      url = 'ru/contact/'

