baseURL = "https://www.example.org/"
title = 'Babalar Press'

disableKinds = ["taxonomy"]


[module]
  [module.hugoVersion]
    extended = true
    min      = "0.112.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"

[languages]

defaultContentLanguage = 'kz'
defaultContentLanguageInSubdir = true

  [languages.kz]
    contentDir = 'content/kz'
    languageCode = 'kk-kz'
    languageName = 'Qazaq'
    weight = 1

  [languages.en]
    contentDir = 'content/en'
    languageCode = 'en-us'
    languageName = 'English'
    weight = 2

  [languages.ru]  
    contentDir = 'content/ru'
    languageCode = 'ru-ru'
    languageName = 'Russian'
    weight = 3


    [[menu.main]]
      identifier = 'home'
      url = '/'
      weight = 10

    [[menu.main]]
      identifier = 'about'
      url = '/about'
      weight = 20

    [[menu.main]]
      identifier = 'contact'
      url = '/contact'
      weight = 30

     [[menu.main]]
      identifier = 'latest'
      url = '/latest'
      weight = 40


    [[menu.main]]
      identifier = 'home'
      url = '/'
      weight = 10

    [[menu.main]]
      identifier = 'about'
      url = '/about'
      weight = 20

    [[menu.main]]
      identifier = 'contact'
      url = '/contact'
      weight = 30

     [[menu.main]]
      identifier = 'latest'
      url = '/latest'
      weight = 40

    [[menu.main]]
      identifier = 'home'
      url = '/'
      weight = 10   

    [[menu.main]]
      identifier = 'about'
      url = '/about'
      weight = 20

    [[menu.main]]
      identifier = 'contact'
      url = '/contact'
      weight = 30

    [[menu.main]]
      identifier = 'latest'
      url = '/latest'
      weight = 40

